/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ChildRouteImport } from './routes/child'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MoreRouteImport } from './routes/more'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as ValueRouteImport } from './routes/value'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAttendanceRouteImport } from './routes/admin.attendance'
import { Route as AdminChildrenRouteImport } from './routes/admin.children'
import { Route as AdminClassesRouteImport } from './routes/admin.classes'
import { Route as AdminStaffRouteImport } from './routes/admin.staff'
import { Route as AdminValuesRouteImport } from './routes/admin.values'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as TeacherActivitiesRouteImport } from './routes/teacher.activities'
import { Route as TeacherAnnouncementsRouteImport } from './routes/teacher.announcements'
import { Route as TeacherAttendanceRouteImport } from './routes/teacher.attendance'
import { Route as TeacherChildrenRouteImport } from './routes/teacher.children'
import { Route as TeacherMessagesRouteImport } from './routes/teacher.messages'
import { Route as TeacherMoreRouteImport } from './routes/teacher.more'
import { Route as TeacherNotificationsRouteImport } from './routes/teacher.notifications'
import { Route as TeacherValueGuideRouteImport } from './routes/teacher.value-guide'
import { Route as TeacherChildIdRouteImport } from './routes/teacher.child.$id'
import { Route as TeacherMessagesIdRouteImport } from './routes/teacher.messages.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildRoute = ChildRouteImport.update({
  id: '/child',
  path: '/child',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const ValueRoute = ValueRouteImport.update({
  id: '/value',
  path: '/value',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAttendanceRoute = AdminAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChildrenRoute = AdminChildrenRouteImport.update({
  id: '/children',
  path: '/children',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClassesRoute = AdminClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminValuesRoute = AdminValuesRouteImport.update({
  id: '/values',
  path: '/values',
  getParentRoute: () => AdminRoute,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherActivitiesRoute = TeacherActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherAnnouncementsRoute = TeacherAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherAttendanceRoute = TeacherAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherChildrenRoute = TeacherChildrenRouteImport.update({
  id: '/children',
  path: '/children',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherMessagesRoute = TeacherMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherMoreRoute = TeacherMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherNotificationsRoute = TeacherNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherValueGuideRoute = TeacherValueGuideRouteImport.update({
  id: '/value-guide',
  path: '/value-guide',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherChildIdRoute = TeacherChildIdRouteImport.update({
  id: '/child/$id',
  path: '/child/$id',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherMessagesIdRoute = TeacherMessagesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TeacherMessagesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/admin': typeof AdminRouteWithChildren
  '/announcements': typeof AnnouncementsRoute
  '/chat': typeof ChatRoute
  '/child': typeof ChildRoute
  '/journey': typeof JourneyRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/more': typeof MoreRoute
  '/parent': typeof ParentRoute
  '/teacher': typeof TeacherRouteWithChildren
  '/value': typeof ValueRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/children': typeof AdminChildrenRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/values': typeof AdminValuesRoute
  '/teacher/activities': typeof TeacherActivitiesRoute
  '/teacher/announcements': typeof TeacherAnnouncementsRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/children': typeof TeacherChildrenRoute
  '/teacher/messages': typeof TeacherMessagesRouteWithChildren
  '/teacher/more': typeof TeacherMoreRoute
  '/teacher/notifications': typeof TeacherNotificationsRoute
  '/teacher/value-guide': typeof TeacherValueGuideRoute
  '/admin/': typeof AdminIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/teacher/child/$id': typeof TeacherChildIdRoute
  '/teacher/messages/$id': typeof TeacherMessagesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/announcements': typeof AnnouncementsRoute
  '/chat': typeof ChatRoute
  '/child': typeof ChildRoute
  '/journey': typeof JourneyRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/more': typeof MoreRoute
  '/parent': typeof ParentRoute
  '/value': typeof ValueRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/children': typeof AdminChildrenRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/values': typeof AdminValuesRoute
  '/teacher/activities': typeof TeacherActivitiesRoute
  '/teacher/announcements': typeof TeacherAnnouncementsRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/children': typeof TeacherChildrenRoute
  '/teacher/messages': typeof TeacherMessagesRouteWithChildren
  '/teacher/more': typeof TeacherMoreRoute
  '/teacher/notifications': typeof TeacherNotificationsRoute
  '/teacher/value-guide': typeof TeacherValueGuideRoute
  '/admin': typeof AdminIndexRoute
  '/teacher': typeof TeacherIndexRoute
  '/teacher/child/$id': typeof TeacherChildIdRoute
  '/teacher/messages/$id': typeof TeacherMessagesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/admin': typeof AdminRouteWithChildren
  '/announcements': typeof AnnouncementsRoute
  '/chat': typeof ChatRoute
  '/child': typeof ChildRoute
  '/journey': typeof JourneyRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/more': typeof MoreRoute
  '/parent': typeof ParentRoute
  '/teacher': typeof TeacherRouteWithChildren
  '/value': typeof ValueRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/children': typeof AdminChildrenRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/values': typeof AdminValuesRoute
  '/teacher/activities': typeof TeacherActivitiesRoute
  '/teacher/announcements': typeof TeacherAnnouncementsRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/children': typeof TeacherChildrenRoute
  '/teacher/messages': typeof TeacherMessagesRouteWithChildren
  '/teacher/more': typeof TeacherMoreRoute
  '/teacher/notifications': typeof TeacherNotificationsRoute
  '/teacher/value-guide': typeof TeacherValueGuideRoute
  '/admin/': typeof AdminIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/teacher/child/$id': typeof TeacherChildIdRoute
  '/teacher/messages/$id': typeof TeacherMessagesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activities'
    | '/admin'
    | '/announcements'
    | '/chat'
    | '/child'
    | '/journey'
    | '/login'
    | '/messages'
    | '/more'
    | '/parent'
    | '/teacher'
    | '/value'
    | '/admin/attendance'
    | '/admin/children'
    | '/admin/classes'
    | '/admin/staff'
    | '/admin/values'
    | '/teacher/activities'
    | '/teacher/announcements'
    | '/teacher/attendance'
    | '/teacher/children'
    | '/teacher/messages'
    | '/teacher/more'
    | '/teacher/notifications'
    | '/teacher/value-guide'
    | '/admin/'
    | '/teacher/'
    | '/teacher/child/$id'
    | '/teacher/messages/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activities'
    | '/announcements'
    | '/chat'
    | '/child'
    | '/journey'
    | '/login'
    | '/messages'
    | '/more'
    | '/parent'
    | '/value'
    | '/admin/attendance'
    | '/admin/children'
    | '/admin/classes'
    | '/admin/staff'
    | '/admin/values'
    | '/teacher/activities'
    | '/teacher/announcements'
    | '/teacher/attendance'
    | '/teacher/children'
    | '/teacher/messages'
    | '/teacher/more'
    | '/teacher/notifications'
    | '/teacher/value-guide'
    | '/admin'
    | '/teacher'
    | '/teacher/child/$id'
    | '/teacher/messages/$id'
  id:
    | '__root__'
    | '/'
    | '/activities'
    | '/admin'
    | '/announcements'
    | '/chat'
    | '/child'
    | '/journey'
    | '/login'
    | '/messages'
    | '/more'
    | '/parent'
    | '/teacher'
    | '/value'
    | '/admin/attendance'
    | '/admin/children'
    | '/admin/classes'
    | '/admin/staff'
    | '/admin/values'
    | '/teacher/activities'
    | '/teacher/announcements'
    | '/teacher/attendance'
    | '/teacher/children'
    | '/teacher/messages'
    | '/teacher/more'
    | '/teacher/notifications'
    | '/teacher/value-guide'
    | '/admin/'
    | '/teacher/'
    | '/teacher/child/$id'
    | '/teacher/messages/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivitiesRoute: typeof ActivitiesRoute
  AdminRoute: typeof AdminRouteWithChildren
  AnnouncementsRoute: typeof AnnouncementsRoute
  ChatRoute: typeof ChatRoute
  ChildRoute: typeof ChildRoute
  JourneyRoute: typeof JourneyRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  MoreRoute: typeof MoreRoute
  ParentRoute: typeof ParentRoute
  TeacherRoute: typeof TeacherRouteWithChildren
  ValueRoute: typeof ValueRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/child': {
      id: '/child'
      path: '/child'
      fullPath: '/child'
      preLoaderRoute: typeof ChildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/value': {
      id: '/value'
      path: '/value'
      fullPath: '/value'
      preLoaderRoute: typeof ValueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/attendance': {
      id: '/admin/attendance'
      path: '/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AdminAttendanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/children': {
      id: '/admin/children'
      path: '/children'
      fullPath: '/admin/children'
      preLoaderRoute: typeof AdminChildrenRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/classes': {
      id: '/admin/classes'
      path: '/classes'
      fullPath: '/admin/classes'
      preLoaderRoute: typeof AdminClassesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/values': {
      id: '/admin/values'
      path: '/values'
      fullPath: '/admin/values'
      preLoaderRoute: typeof AdminValuesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/activities': {
      id: '/teacher/activities'
      path: '/activities'
      fullPath: '/teacher/activities'
      preLoaderRoute: typeof TeacherActivitiesRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/announcements': {
      id: '/teacher/announcements'
      path: '/announcements'
      fullPath: '/teacher/announcements'
      preLoaderRoute: typeof TeacherAnnouncementsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/attendance': {
      id: '/teacher/attendance'
      path: '/attendance'
      fullPath: '/teacher/attendance'
      preLoaderRoute: typeof TeacherAttendanceRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/children': {
      id: '/teacher/children'
      path: '/children'
      fullPath: '/teacher/children'
      preLoaderRoute: typeof TeacherChildrenRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/messages': {
      id: '/teacher/messages'
      path: '/messages'
      fullPath: '/teacher/messages'
      preLoaderRoute: typeof TeacherMessagesRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/more': {
      id: '/teacher/more'
      path: '/more'
      fullPath: '/teacher/more'
      preLoaderRoute: typeof TeacherMoreRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/notifications': {
      id: '/teacher/notifications'
      path: '/notifications'
      fullPath: '/teacher/notifications'
      preLoaderRoute: typeof TeacherNotificationsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/value-guide': {
      id: '/teacher/value-guide'
      path: '/value-guide'
      fullPath: '/teacher/value-guide'
      preLoaderRoute: typeof TeacherValueGuideRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/child/$id': {
      id: '/teacher/child/$id'
      path: '/child/$id'
      fullPath: '/teacher/child/$id'
      preLoaderRoute: typeof TeacherChildIdRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/messages/$id': {
      id: '/teacher/messages/$id'
      path: '/$id'
      fullPath: '/teacher/messages/$id'
      preLoaderRoute: typeof TeacherMessagesIdRouteImport
      parentRoute: typeof TeacherMessagesRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAttendanceRoute: typeof AdminAttendanceRoute
  AdminChildrenRoute: typeof AdminChildrenRoute
  AdminClassesRoute: typeof AdminClassesRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminValuesRoute: typeof AdminValuesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAttendanceRoute: AdminAttendanceRoute,
  AdminChildrenRoute: AdminChildrenRoute,
  AdminClassesRoute: AdminClassesRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminValuesRoute: AdminValuesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface TeacherMessagesRouteChildren {
  TeacherMessagesIdRoute: typeof TeacherMessagesIdRoute
}

const TeacherMessagesRouteChildren: TeacherMessagesRouteChildren = {
  TeacherMessagesIdRoute: TeacherMessagesIdRoute,
}

const TeacherMessagesRouteWithChildren = TeacherMessagesRoute._addFileChildren(
  TeacherMessagesRouteChildren,
)

interface TeacherRouteChildren {
  TeacherActivitiesRoute: typeof TeacherActivitiesRoute
  TeacherAnnouncementsRoute: typeof TeacherAnnouncementsRoute
  TeacherAttendanceRoute: typeof TeacherAttendanceRoute
  TeacherChildrenRoute: typeof TeacherChildrenRoute
  TeacherMessagesRoute: typeof TeacherMessagesRouteWithChildren
  TeacherMoreRoute: typeof TeacherMoreRoute
  TeacherNotificationsRoute: typeof TeacherNotificationsRoute
  TeacherValueGuideRoute: typeof TeacherValueGuideRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
  TeacherChildIdRoute: typeof TeacherChildIdRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherActivitiesRoute: TeacherActivitiesRoute,
  TeacherAnnouncementsRoute: TeacherAnnouncementsRoute,
  TeacherAttendanceRoute: TeacherAttendanceRoute,
  TeacherChildrenRoute: TeacherChildrenRoute,
  TeacherMessagesRoute: TeacherMessagesRouteWithChildren,
  TeacherMoreRoute: TeacherMoreRoute,
  TeacherNotificationsRoute: TeacherNotificationsRoute,
  TeacherValueGuideRoute: TeacherValueGuideRoute,
  TeacherIndexRoute: TeacherIndexRoute,
  TeacherChildIdRoute: TeacherChildIdRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivitiesRoute: ActivitiesRoute,
  AdminRoute: AdminRouteWithChildren,
  AnnouncementsRoute: AnnouncementsRoute,
  ChatRoute: ChatRoute,
  ChildRoute: ChildRoute,
  JourneyRoute: JourneyRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  MoreRoute: MoreRoute,
  ParentRoute: ParentRoute,
  TeacherRoute: TeacherRouteWithChildren,
  ValueRoute: ValueRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
