/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ChildRouteImport } from './routes/child'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MoreRouteImport } from './routes/more'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as ValueRouteImport } from './routes/value'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as TeacherAttendanceRouteImport } from './routes/teacher.attendance'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildRoute = ChildRouteImport.update({
  id: '/child',
  path: '/child',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const ValueRoute = ValueRouteImport.update({
  id: '/value',
  path: '/value',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherAttendanceRoute = TeacherAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => TeacherRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/announcements': typeof AnnouncementsRoute
  '/chat': typeof ChatRoute
  '/child': typeof ChildRoute
  '/journey': typeof JourneyRoute
  '/messages': typeof MessagesRoute
  '/more': typeof MoreRoute
  '/teacher': typeof TeacherRouteWithChildren
  '/value': typeof ValueRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/': typeof TeacherIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/announcements': typeof AnnouncementsRoute
  '/chat': typeof ChatRoute
  '/child': typeof ChildRoute
  '/journey': typeof JourneyRoute
  '/messages': typeof MessagesRoute
  '/more': typeof MoreRoute
  '/value': typeof ValueRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher': typeof TeacherIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/announcements': typeof AnnouncementsRoute
  '/chat': typeof ChatRoute
  '/child': typeof ChildRoute
  '/journey': typeof JourneyRoute
  '/messages': typeof MessagesRoute
  '/more': typeof MoreRoute
  '/teacher': typeof TeacherRouteWithChildren
  '/value': typeof ValueRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/': typeof TeacherIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activities'
    | '/announcements'
    | '/chat'
    | '/child'
    | '/journey'
    | '/messages'
    | '/more'
    | '/teacher'
    | '/value'
    | '/teacher/attendance'
    | '/teacher/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activities'
    | '/announcements'
    | '/chat'
    | '/child'
    | '/journey'
    | '/messages'
    | '/more'
    | '/value'
    | '/teacher/attendance'
    | '/teacher'
  id:
    | '__root__'
    | '/'
    | '/activities'
    | '/announcements'
    | '/chat'
    | '/child'
    | '/journey'
    | '/messages'
    | '/more'
    | '/teacher'
    | '/value'
    | '/teacher/attendance'
    | '/teacher/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivitiesRoute: typeof ActivitiesRoute
  AnnouncementsRoute: typeof AnnouncementsRoute
  ChatRoute: typeof ChatRoute
  ChildRoute: typeof ChildRoute
  JourneyRoute: typeof JourneyRoute
  MessagesRoute: typeof MessagesRoute
  MoreRoute: typeof MoreRoute
  TeacherRoute: typeof TeacherRouteWithChildren
  ValueRoute: typeof ValueRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/child': {
      id: '/child'
      path: '/child'
      fullPath: '/child'
      preLoaderRoute: typeof ChildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/value': {
      id: '/value'
      path: '/value'
      fullPath: '/value'
      preLoaderRoute: typeof ValueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/attendance': {
      id: '/teacher/attendance'
      path: '/attendance'
      fullPath: '/teacher/attendance'
      preLoaderRoute: typeof TeacherAttendanceRouteImport
      parentRoute: typeof TeacherRoute
    }
  }
}

interface TeacherRouteChildren {
  TeacherAttendanceRoute: typeof TeacherAttendanceRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherAttendanceRoute: TeacherAttendanceRoute,
  TeacherIndexRoute: TeacherIndexRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivitiesRoute: ActivitiesRoute,
  AnnouncementsRoute: AnnouncementsRoute,
  ChatRoute: ChatRoute,
  ChildRoute: ChildRoute,
  JourneyRoute: JourneyRoute,
  MessagesRoute: MessagesRoute,
  MoreRoute: MoreRoute,
  TeacherRoute: TeacherRouteWithChildren,
  ValueRoute: ValueRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
